### ISSUE TITLE
the governance and life cycle workspaces/collections are unavailable

### ISSUE THREAD

**Issue by jarrodparkes** [union-fashion/home#10]
I'm supremely interested in the Governance and Life Cycle workspaces, collections, and examples. These seem like extremely meaty portions of the API-design process, but I'm having trouble finding links to collections (or something that could be imported as a collection), etc. I would love to be able to use/fork them.

> You can **view the details for the Union Fashion life cycle**, and run the API life cycle collection within any workspace for managing an API--using the collection as guardrails and checklist for the entire API life cycle.

^ this link is broken in the **Life Cycle** and for **Governance** sections of the README.md

I'm also unable to get any of the "Run in Postman" links to actually open in Postman, but that may be unrelated

**Comment by kinlane** [comment]
Hey there. Thanks for your interest. I fixed the links and republished (apologies). So this should have what you need. 

URL - https://github.com/union-fashion/operations

Let me know your thoughts about where I should go next with it.

**Comment by jarrodparkes** [comment]
Wonderful. Thank you for doing this!

What (or where) would be the best way to provide feedback?

**Comment by kinlane** [comment]
I prefer having as GitHub issues so others can learn from, so just post as issues, individual or grouped, and I'll work through. If you'd rather it not all be public, feel free to just email me at kinlane@gmail.com. 

I am very thankful for another pair of eyes and thoughts on where to steer this beast. So many ways I could go. Need grounding. ;-)
