### ISSUE TITLE
Any hints where to get the collections for Deployment and Monitoring covered in the webinar today?

### ISSUE THREAD

**Issue by fortran01** [union-fashion/home#12]
- https://github.com/union-fashion/home/blob/master/planning/deploy-and-monitor-planning.md#deployment

- https://github.com/union-fashion/home/blob/master/planning/deploy-and-monitor-planning.md#monitoring

🙏

**Comment by kinlane** [comment]
You can find it here - https://github.com/union-fashion/operations

**Comment by fortran01** [comment]
Private repo, right?

**Comment by kinlane** [comment]
All the repos for this project are open.

**Comment by fortran01** [comment]
I get a 404 here https://github.com/union-fashion/operations. Any hints?

**Comment by kinlane** [comment]
Ahhh. sorry.  I see. I made public.
